---

- name: Create wide IP
  bigip_gtm_wide_ip:
      lb_method: "{{ lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Create wide IP
  assert:
      that:
          - result|changed

- name: Create wide IP - Idempotent check
  bigip_gtm_wide_ip:
      lb_method: "{{ lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Create wide IP - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set wide IP LB method, valid
  bigip_gtm_wide_ip:
      lb_method: "{{ lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  with_items: valid_lb_methods

- name: Set wide IP LB method, invalid
  bigip_gtm_wide_ip:
      lb_method: "{{ lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  with_items: invalid_lb_methods
  ignore_errors: true

- name: Delete wide IP
  bigip_gtm_wide_ip:
      lb_method: "{{ lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "absent"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Delete wide IP
  assert:
      that:
          - result|changed

- name: Delete wide IP - Idempotent check
  bigip_gtm_wide_ip:
      lb_method: "{{ lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "absent"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Delete wide IP - Idempotent check
  assert:
      that:
          - not result|changed