---

- name: Delete iRule with space at the end - Setup
  bigip_irule:
      module: "ltm"
      name: "issue-42"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Create iRule with space at the end
  bigip_irule:
      content: "when HTTP_REQUEST {HTTP::respond 200 content 'Good Request'}\n"
      module: "ltm"
      name: "issue-42"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create iRule with space at the end
  assert:
      that:
          - result|changed

- name: Create iRule with space at the end - Idempotent check
  bigip_irule:
      content: "when HTTP_REQUEST {HTTP::respond 200 content 'Good Request'}\n"
      module: "ltm"
      name: "issue-42"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create iRule with space at the end - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete iRule with space at the end - Teardown
  bigip_irule:
      module: "ltm"
      name: "issue-42"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete iRule with space at the end - Teardown
  assert:
      that:
          - result|changed