sudo: false

language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"

install:
    - pip install -r requirements.test.txt

script:
    - make all-tests
    - bash test/ansible/sanity/integration-test-idempotent-names.sh
    - ./test/ansible/sanity/short-description-ends-with-period.py
    - pycodestyle library/
    - pycodestyle test/unit/bigip/
    - pycodestyle test/unit/bigiq/
    - pycodestyle test/unit/iworkflow/
