sudo: required

language: python

python:
  - 2.7
  - 2.6
  - 3.5
  - 3.6

env:
  - TOXENV=unit
  - TOXENV=flake

before_install:
  # NOTE: this is probably not required since you're not trying to pull or
  # push from a GitHub repo
  - git config --global user.email "OpenStack_TravisCI@f5.com"
  - git config --global user.name "Travis F5 Openstack"

install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get -y install libffi-dev libssl-dev
  - travis_retry pip install --upgrade setuptools pip
  - travis_retry pip install cffi
  - travis_retry pip install --upgrade -r requirements.test.txt

script:
  - tox

jobs:
  include:
    - stage: test
      script: tox
      python: 3.5
      env: TOXENV=docs
      if: branch = devel

    - stage: deploy
      script: make docker-deploy
      python: 3.5
      env: TOXENV=docs
      if: branch = devel
