sudo: false

language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"

install:
    - pip install flake8
    - pip install markupsafe ansible==1.9.4

script:
    - make all-tests
