sudo: false

language: python

addons:
    apt:
        packages:
            - python-dev

python:
    - "2.7"
    - "2.6"

before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"

install:
    - pip install flake8
    - pip install markupsafe ansible==1.9.4

script:
    - make all-tests
