---

- name: Run show version on remote devices
  bigip_command:
      commands:
          - tmsh show sys version
      provider: "{{ cli }}"
  register: result

- name: Run show sys clock
  bigip_command:
      commands:
          - "tmsh show sys clock"
      provider: "{{ cli }}"
  register: result

- name: Run list auth
  bigip_command:
      commands:
          - "tmsh list auth"
      provider: "{{ cli }}"
  register: result