---

- name: Create pool, type 'a'
  bigip_gtm_pool:
      preferred_lb_method: "{{ pool_lb_method }}"
      name: "{{ pool_name }}"
      state: "present"
      type: "a"
  register: result

- name: Assert Create pool, type 'a'
  assert:
      that:
          - result|changed

- name: Create pool, type 'a' - idempotent check
  bigip_gtm_pool:
      preferred_lb_method: "{{ pool_lb_method }}"
      name: "{{ pool_name }}"
      state: "present"
      type: "a"
  register: result

- name: Assert Create pool, 'a' - idempotent check
  assert:
      that:
          - not result|changed

- name: Change pool type 'a' lb_method to ratio
  bigip_gtm_pool:
      preferred_lb_method: "{{ pool_lb_method_alt[2] }}"
      name: "{{ pool_name }}"
      state: "present"
      type: "a"
  register: result

- name: Assert Change pool type 'a' lb_method to ratio
  assert:
      that:
          - result|changed

- name: Change pool type 'a' lb_method to ratio - Idempotent check
  bigip_gtm_pool:
      preferred_lb_method: "{{ pool_lb_method_alt[2] }}"
      name: "{{ pool_name }}"
      state: "present"
      type: "a"
  register: result

- name: Assert Change pool type 'a' lb_method to ratio - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete pool
  bigip_gtm_pool:
      name: "{{ pool_name }}"
      state: "absent"
      type: "a"
  register: result

- name: Assert Delete pool
  assert:
      that:
          - result|changed

- name: Delete pool - idempotent check
  bigip_gtm_pool:
      name: "{{ pool_name }}"
      state: "absent"
      type: "a"
  register: result

- name: Assert Delete pool - idempotent check
  assert:
      that:
          - not result|changed
