---

- name: Create iRule in LTM
  bigip_irule:
      content: "{{ lookup('template', 'irule-01.tcl') }}"
      module: "ltm"
      name: "{{ irule_name_ltm }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create iRule in LTM
  assert:
      that:
          - result|changed

- name: Create iRule in LTM - Idempotent check
  bigip_irule:
      content: "{{ lookup('template', 'irule-01.tcl') }}"
      module: "ltm"
      name: "{{ irule_name_ltm }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create iRule in LTM - Idempotent check
  assert:
      that:
          - not result|changed

- name: Modify iRule in LTM
  bigip_irule:
      content: "{{ lookup('template', 'irule-01.tcl') }}"
      module: "ltm"
      name: "{{ irule_name_ltm }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Modify iRule in LTM
  assert:
      that:
          - result|changed

- name: Modify iRule in LTM - Idempotent check
  bigip_irule:
      content: "{{ lookup('template', 'irule-01.tcl') }}"
      module: "ltm"
      name: "{{ irule_name_ltm }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Modify iRule in LTM - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete iRule in LTM
  bigip_irule:
      module: "ltm"
      name: "{{ irule_name_ltm }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete iRule in LTM
  assert:
      that:
          - result|changed

- name: Delete iRule in LTM - Idempotent check
  bigip_irule:
      module: "ltm"
      name: "{{ irule_name_ltm }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete iRule in LTM - Idempotent check
  assert:
      that:
          - not result|changed

- name: Create iRule in GTM
  bigip_irule:
      content: "{{ lookup('template', 'irule-02.tcl') }}"
      module: "gtm"
      name: "{{ irule_name_gtm }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create iRule in GTM
  assert:
      that:
          - not result|changed
