---

- name: Create tenant
  iworkflow_tenant:
      name: "{{ tenant_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result

- name: Create connector
  iworkflow_local_connector:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result
  with_items:
      - "{{ connector_name1 }}"
      - "{{ connector_name2 }}"

- name: Register connector to tenant
  iworkflow_tenant_connector:
      tenant: "{{ tenant_name }}"
      connectors: "{{ connector_name1 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result

- fail: msg="ASDasd"

- name: Assert Register connector to tenant
  assert:
      that:
          - result|changed

- name: Register connector to tenant - Idempotent check
  iworkflow_tenant_connector:
      tenant: "{{ tenant_name }}"
      connectors: "{{ connector_name1 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result

- name: Assert Register connector to tenant - Idempotent check
  assert:
      that:
          - not result|changed

- name: Register multiple connectors to tenant
  iworkflow_tenant_connector:
      tenant: "{{ tenant_name }}"
      connectors:
          - "{{ connector_name1 }}"
          - "{{ connector_name2 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result

- name: Assert Register second connector to tenant
  assert:
      that:
          - result|changed

- name: Unregister connector from tenant
  iworkflow_tenant_connector:
      tenant: "{{ tenant_name }}"
      connectors: "{{ connector_name1 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result

- name: Assert Unregister connector from tenant
  assert:
      that:
          - result|changed

- name: Unregister connector from tenant - Idempotent check
  iworkflow_tenant_connector:
      tenant: "{{ tenant_name }}"
      connectors: "{{ connector_name1 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result

- name: Assert Unregister connector from tenant - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete connector
  iworkflow_local_connector:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result
  with_items:
      - "{{ connector_name1 }}"
      - "{{ connector_name2 }}"

- name: Delete tenant
  iworkflow_tenant:
      name: "{{ tenant_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result
