---

- name: Discover BIG-IP
  iworkflow_device:
      device: "{{ device_ip1 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      username_credential: "{{ bigip_username }}"
      password_credential: "{{ bigip_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  delegate_to: localhost

- name: Create connector
  iworkflow_local_connector:
      name: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result

- name: Register device to connector
  iworkflow_local_connector_device:
      device: "{{ device_name1 }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result

- name: Assert Register device to connector
  assert:
      that:
          - result|changed

- name: Register device to connector - Idempotent check
  iworkflow_local_connector_device:
      device: "{{ device_name1 }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result

- name: Assert Register device to connector - Idempotent check
  assert:
      that:
          - not result|changed

- name: Unregister device from connector
  iworkflow_local_connector_device:
      device: "{{ device_name1 }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result

- name: Assert Unregister device from connector
  assert:
      that:
          - result|changed

- name: Unregister device from connector - Idempotent check
  iworkflow_local_connector_device:
      device: "{{ device_name1 }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result

- name: Assert Unregister device from connector - Idempotent check
  assert:
      that:
          - not result|changed

- name: Register multiple devices to connector
  iworkflow_local_connector_device:
      device: "{{ item }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result
  with_items:
      - "{{ device_name1 }}"

- name: Assert Register multiple devices to connector
  assert:
      that:
          - result|changed

- name: Register multiple devices to connector - Idempotent check
  iworkflow_local_connector_device:
      device: "{{ item }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "present"
  register: result
  with_items:
      - "{{ device_name1 }}"

- name: Assert Register multiple devices to connector - Idempotent check
  assert:
      that:
          - not result|changed

- name: Unregister multiple devices from connector
  iworkflow_local_connector_device:
      device: "{{ item }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result
  with_items:
      - "{{ device_name1 }}"

- name: Assert Unregister multiple devices from connector
  assert:
      that:
          - result|changed

- name: Unregister multiple devices from connector - Idempotent check
  iworkflow_local_connector_device:
      device: "{{ item }}"
      connector: "{{ connector_name }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result
  with_items:
      - "{{ device_name1 }}"

- name: Assert Unregister multiple devices from connector - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete connector
  iworkflow_local_connector:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result
  with_items:
      - "{{ connector_name }}"

- name: Undiscover BIG-IP
  iworkflow_device:
      device: "{{ device_ip1 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ iworkflow_port }}"
      user: "{{ iworkflow_username }}"
      password: "{{ iworkflow_password }}"
      username_credential: "{{ bigip_username }}"
      password_credential: "{{ bigip_password }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  delegate_to: localhost
