---

- name: Remove Self IPs
  bigip_selfip:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: "absent"
  register: result
  with_items:
      - net1
      - net2

- name: Remove VLANs
  bigip_vlan:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: "absent"
  register: result
  with_items:
      - net1
      - net2
      - vlan1