---

# We use clouds.yaml for both the CLI and Ansible configurations
#
# @see: https://docs.openstack.org/python-openstackclient/latest/configuration/index.html
#

version: '3.3'

# Networks need to be overridden from their defaults to avoid address space
# conflicts on site.
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 2.2.2.0/24
services:
  py2.7.10:
    image: f5ansible/py2.7.10
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py2.7.10
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
      - source: .gitconfig
        target: .gitconfig
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
      - type: bind
        source: ~/.gnupg
        target: /gpg
    environment:
      - OS_CLOUD=default
      - PYTHONDONTWRITEBYTECODE=1
      - GNUPGHOME=/gpg/
      - GPG=/usr/local/bin/gpg2
  py2.7.10-bare:
    image: f5ansible/py2.7.10-bare
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py2.7.10-bare
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
      - source: .gitconfig
        target: .gitconfig
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
      - type: bind
        source: ~/.gnupg
        target: /gpg
    environment:
      - OS_CLOUD=default
      - PYTHONDONTWRITEBYTECODE=1
      - GNUPGHOME=/gpg/
      - GPG=/usr/local/bin/gpg2
  py3.5.4:
    image: f5ansible/py3.5.4
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py3.5.4
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
      - source: .gitconfig
        target: .gitconfig
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
      - type: bind
        source: ~/.gnupg
        target: /gpg
    environment:
      - OS_CLOUD=default
      - PYTHONDONTWRITEBYTECODE=1
      - GNUPGHOME=/gpg/
      - GPG=/usr/local/bin/gpg2
  py3.5.4-bare:
    image: f5ansible/py3.5.4-bare
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py3.5.4-bare
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
      - source: .gitconfig
        target: .gitconfig
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
      - type: bind
        source: ~/.gnupg
        target: /gpg
    environment:
      - OS_CLOUD=default
      - PYTHONDONTWRITEBYTECODE=1
      - GNUPGHOME=/gpg/
      - GPG=/usr/local/bin/gpg2
  py3.6.2:
    image: f5ansible/py3.6.2
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py3.6.2
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
      - source: .gitconfig
        target: .gitconfig
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
      - type: bind
        source: ~/.gnupg
        target: /gpg
    environment:
      - OS_CLOUD=default
      - PYTHONDONTWRITEBYTECODE=1
      - GNUPGHOME=/gpg/
      - GPG=/usr/local/bin/gpg2
  py3.6.2-bare:
    image: f5ansible/py3.6.2-bare
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py3.6.2-bare
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
      - source: .gitconfig
        target: .gitconfig
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
      - type: bind
        source: ~/.gnupg
        target: /gpg
    environment:
      - OS_CLOUD=default
      - PYTHONDONTWRITEBYTECODE=1
      - GNUPGHOME=/gpg/
      - GPG=/usr/local/bin/gpg2
secrets:
  clouds.yaml:
    file: ./secrets/clouds.yaml.secret
  secure.yaml:
    file: ./secrets/secure.yaml.secret
  cacerts.pem:
    file: ./secrets/cacerts.pem.secret
  .gitconfig:
    file: ./secrets/gitconfig.secret
