version: '3.1'
services:
  python-2.7:
    build:
      context: ..
      dockerfile: ./devtools/Dockerfile
    command: /bin/bash
secrets:
  clouds.yaml:
    file: ./clouds.yaml.secret
  secure.yaml:
    file: ./secure.yaml.secret
