---

# We use clouds.yaml for both the CLI and Ansible configurations
#
# @see: https://docs.openstack.org/python-openstackclient/latest/configuration/index.html
#

version: '3.3'
services:
  py2.7.10:
    image: f5ansible/py2.7.10
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py2.7.10
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
    environment:
      - OS_CLOUD=default
  py3.5.4:
    image: f5ansible/py3.5.4
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py3.5.4
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
    environment:
      - OS_CLOUD=default
  py3.6.2:
    image: f5ansible/py3.6.2
    build:
      context: ..
      dockerfile: ./devtools/dockerfiles/Dockerfile-py3.6.2
    command: /bin/bash
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
      - source: secure.yaml
        target: secure.yaml
      - source: cacerts.pem
        target: cacerts.pem
    extra_hosts:
      - "localhost:1.2.3.4"
    volumes:
      - type: bind
        source: ../
        target: /here
    environment:
      - OS_CLOUD=default
secrets:
  clouds.yaml:
    file: ./secrets/clouds.yaml.secret
  secure.yaml:
    file: ./secrets/secure.yaml.secret
  cacerts.pem:
    file: ./secrets/cacerts.pem.secret
