---

- name: Upload 12.0.0 base image
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Upload 12.0.0 base image
  assert:
      that:
          - result|changed

- name: Upload 12.0.0 base image - Idempotent check
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Upload 12.0.0 base image - Idempotent check
  assert:
      that:
          - not result|changed

- name: Upload 12.0.0 HF1 hotfix image
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Upload 12.0.0 HF1 hotfix image
  assert:
      that:
          - result|changed

- name: Upload 12.0.0 HF1 hotfix image - Idempotent check
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Upload 12.0.0 HF1 hotfix image - Idempotent check
  assert:
      that:
          - not result|changed

- name: Remove uploaded 12.0.0 base image
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove uploaded 12.0.0 base image
  assert:
      that:
          - result|changed

- name: Remove uploaded 12.0.0 base image - Idempotent check
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove uploaded 12.0.0 base image - Idempotent check
  assert:
      that:
          - not result|changed

- name: Remove uploaded 12.0.0 HF1 hotfix image
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove uploaded 12.0.0 HF1 hotfix image
  assert:
      that:
          - result|changed

- name: Remove uploaded 12.0.0 HF1 hotfix image - Idempotent check
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove uploaded 12.0.0 HF1 hotfix image - Idempotent check
  assert:
      that:
          - not result|changed

- name: Upload base image and hotfix
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Upload base image and hotfix
  assert:
      that:
          - result|changed

- name: Upload base image and hotfix - Idempotent check
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Upload base image and hotfix - Idempotent check
  assert:
      that:
          - not result|changed

- name: Remove uploaded base image and hotfix
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove uploaded base image and hotfix
  assert:
      that:
          - result|changed

- name: Remove uploaded base image and hotfix - Idempotent check
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove uploaded base image and hotfix - Idempotent check
  assert:
      that:
          - not result|changed

- name: Install (upload, install) base image
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "installed"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_new }}"
  register: result

- name: Assert Install (upload, install) base image
  assert:
      that:
          - result|changed

- name: Install (upload, install) base image - Idempotent check
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "installed"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_new }}"
  register: result

- name: Assert Install (upload, install) base image - Idempotent check
  assert:
      that:
          - not result|changed

- name: Install (upload, install) base image and hotfix
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "installed"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_new }}"
  register: result

- name: Assert Install (upload, install) base image and hotfix
  assert:
      that:
          - result|changed

- name: Install (upload, install) base image and hotfix - Idempotent check
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "installed"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_new }}"
  register: result

- name: Assert Install (upload, install) base image and hotfix - Idempotent check
  assert:
      that:
          - not result|changed

- name: Activate (upload, install, reboot) base image
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "activated"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_new }}"
  register: result

- name: Assert Activate (upload, install, reboot) base image
  assert:
      that:
          - result|changed

- name: Activate (upload, install, reboot, reuse_inactive_volume) base image
  bigip_software:
      password: "{{ bigip_password }}"
      reuse_inactive_volume: True
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "activated"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Activate (upload, install, reboot) base image
  assert:
      that:
          - result|changed

- name: Activate (upload, install, reboot) base image - Idempotent check
  bigip_software:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "activated"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_new }}"
  register: result

- name: Assert Activate (upload, install, reboot) base image - Idempotent check
  assert:
      that:
          - not result|changed

- name: Activate (upload, install, reboot) base image and hotfix
  bigip_software:
      hotfix: "{{ iso_hostfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "activated"
      user: "{{ bigip_user }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_old }}"
  register: result

- name: Assert Activate (upload, install, reboot) base image and hotfix
  assert:
      that:
          - result|changed

- name: Activate (upload, install, reboot) base image and hotfix - Idempotent check
  bigip_software:
      hotfix: "{{ iso_hotfix }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      software: "{{ iso_base }}"
      state: "activated"
      user: "{{ bigip_user }}"
      validate_certs: "{{ validate_certs }}"
      volume: "{{ volume_old }}"
  register: result

- name: Assert Activate (upload, install, reboot) base image and hotfix - Idempotent check
  assert:
      that:
          - not result|changed
