---

- name: Remove Self IPs
  bigip_selfip:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: "absent"
  register: result
  with_items:
      - net1
      - net2

- name: Remove VLANs
  bigip_vlan:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: "absent"
  register: result
  with_items:
      - net1
      - net2
      - vlan1

- name: Create VLANs
  bigip_vlan:
      name: "{{ item }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: "present"
  register: result
  with_items:
      - net1

- name: Create route domain
  bigip_routedomain:
      id: "{{ selfip_rd }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      validate_certs: "{{ validate_certs }}"
      vlans:
          - net1
  register: result

- name: Assert Create route domain
  assert:
      that:
          - result|changed