---

ansible_host: IP_A0

self_ips:
  - name: Self-Internal
    address: IP_A1
    netmask: 255.255.255.0
    vlan: Internal
  - name: Self-External
    address: IP_A2
    netmask: 255.255.255.0
    vlan: External
  - name: Self-HA
    address: IP_A3
    netmask: 255.255.255.0
    vlan: HA

config_sync_ip: IP_A3
mirror_primary_address: IP_A3
unicast_failover:
  - address: IP_A3
