---

ansible_host: 10.10.10.10

self_ips:
  - name: Self-Internal
    address: 10.1.10.1
    netmask: 255.255.255.0
    vlan: Internal
  - name: Self-External
    address: 10.1.20.1
    netmask: 255.255.255.0
    vlan: External
  - name: Self-HA
    address: 10.1.30.1
    netmask: 255.255.255.0
    vlan: HA

config_sync_ip: 10.1.30.1
mirror_primary_address: 10.1.30.1
unicast_failover:
  - address: 10.1.30.1
