---

- name: Create snmp v1 trap
  bigip_snmp_trap:
      community: "{{ community1 }}"
      destination: "{{ destination1 }}"
      name: "{{ trap_name1 }}"
      network: "{{ network1 }}"
      port: "{{ port1 }}"
      snmp_version: "{{ version1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create snmp v1 trap
  assert:
      that:
          - result|changed

- name: Create snmp v1 trap - Idempotent check
  bigip_snmp_trap:
      community: "{{ community1 }}"
      destination: "{{ destination1 }}"
      name: "{{ trap_name1 }}"
      network: "{{ network1 }}"
      port: "{{ port1 }}"
      snmp_version: "{{ version1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create snmp v1 trap - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set snmp community
  bigip_snmp_trap:
      community: "{{ community2 }}"
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp community
  assert:
      that:
          - result|changed

- name: Set snmp community - Idempotent check
  bigip_snmp_trap:
      community: "{{ community2 }}"
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp community - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set snmp destination to a hostname
  bigip_snmp_trap:
      destination: "{{ destination2 }}"
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp destination to a hostname
  assert:
      that:
          - result|changed

- name: Set snmp destination to a hostname - Idempotent check
  bigip_snmp_trap:
      destination: "{{ destination2 }}"
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp destination to a hostname - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set snmp port
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      port: "{{ port2 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp port
  assert:
      that:
          - result|changed

- name: Set snmp port - Idempotent check
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      port: "{{ port2 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp port - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set snmp network to default
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      network: "{{ network2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp network to default
  assert:
      that:
          - result|changed

- name: Set snmp network to default - Idempotent check
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      network: "{{ network2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp network to default - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set snmp network to other
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      network: "{{ network3 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp network to other
  assert:
      that:
          - result|changed

- name: Set snmp network to other - Idempotent check
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      network: "{{ network3 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set snmp network to other - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set snmp version to 2c
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      snmp_version: "{{ version2 }}"
  register: result

- name: Assert Set snmp version to 2c
  assert:
      that:
          - result|changed

- name: Set snmp version to 2c - Idempotent check
  bigip_snmp_trap:
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      snmp_version: "{{ version2 }}"
  register: result

- name: Assert Set snmp version to 2c - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete an snmp trap
  bigip_snmp_trap:
      destination: "{{ destination2 }}"
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result

- name: Assert Delete an snmp trap
  assert:
      that:
          - result|changed

- name: Delete an snmp trap - Idempotent check
  bigip_snmp_trap:
      destination: "{{ destination2 }}"
      name: "{{ trap_name1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      state: "absent"
  register: result

- name: Assert Delete an snmp trap - Idempotent check
  assert:
      that:
          - not result|changed