---

- name: Create wide IP
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Create wide IP
  assert:
      that:
          - result|changed

- name: Create wide IP - Idempotent check
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Create wide IP - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set wide IP LB method, valid - ratio
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Set wide IP LB method, valid - ratio
  assert:
      that:
          - result|changed

- name: Set wide IP LB method, valid - ratio - Idempotent check
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Set wide IP LB method, valid - ratio - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set wide IP LB method, valid - topology
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method3 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Set wide IP LB method, valid - topology
  assert:
      that:
          - result|changed

- name: Set wide IP LB method, valid - topology - Idempotent check
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method3 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Set wide IP LB method, valid - topology - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set wide IP LB method, valid - global availability
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method4 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Set wide IP LB method, valid - global availability
  assert:
      that:
          - result|changed

- name: Set wide IP LB method, valid - global availability - Idempotent check
  bigip_gtm_wide_ip:
      lb_method: "{{ valid_lb_method4 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Set wide IP LB method, valid - global availability - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set wide IP LB method, invalid 1
  bigip_gtm_wide_ip:
      lb_method: "{{ invalid_lb_method1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result
  ignore_errors: true

- name: Assert Set wide IP LB method, invalid 1
  assert:
      that:
          - not result|changed

- name: Set wide IP LB method, invalid 2
  bigip_gtm_wide_ip:
      lb_method: "{{ invalid_lb_method2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result
  ignore_errors: true

- name: Assert Set wide IP LB method, invalid 2
  assert:
      that:
          - not result|changed

- name: Set wide IP LB method, invalid 3
  bigip_gtm_wide_ip:
      lb_method: "{{ invalid_lb_method3 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "present"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result
  ignore_errors: true

- name: Assert Set wide IP LB method, invalid 3
  assert:
      that:
          - not result|changed

- name: Delete wide IP
  bigip_gtm_wide_ip:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "absent"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Delete wide IP
  assert:
      that:
          - result|changed

- name: Delete wide IP - Idempotent check
  bigip_gtm_wide_ip:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      state: "absent"
      type: "a"
      validate_certs: "{{ validate_certs }}"
      wide_ip: "{{ wide_ip1 }}"
  register: result

- name: Assert Delete wide IP - Idempotent check
  assert:
      that:
          - not result|changed
