---

- name: Create TCP Monitor
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      receive: "{{ receive_string }}"
      send: "{{ send_string }}"
      state: "present"
      type: "tcp"
  register: result

- name: Assert Create TCP Monitor
  assert:
      that:
          - result|changed

- name: Create TCP Monitor - Idempotent check
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      receive: "{{ receive_string }}"
      send: "{{ send_string }}"
      state: "present"
      type: "tcp"
  register: result

- name: Assert Create TCP Monitor - Idempotent check
  assert:
      that:
          - not result|changed

- name: Remove TCP Monitor
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      state: "absent"
  register: result

- name: Assert Remove TCP Monitor
  assert:
      that:
          - result|changed

- name: Remove TCP Monitor - Idempotent check
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      state: "absent"
  register: result

- name: Assert Remove TCP Monitor - Idempotent check
  assert:
      that:
          - not result|changed
