---

- name: Create TCP Monitor
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      password: "{{ bigip_password }}"
      receive: "{{ receive_string }}"
      send: "{{ send_string }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "present"
      type: "tcp"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create TCP Monitor
  assert:
      that:
          - result|changed

- name: Create TCP Monitor - Idempotent check
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      password: "{{ bigip_password }}"
      receive: "{{ receive_string }}"
      send: "{{ send_string }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "present"
      type: "tcp"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Create TCP Monitor - Idempotent check
  assert:
      that:
          - not result|changed

- name: Remove TCP Monitor
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove TCP Monitor
  assert:
      that:
          - result|changed

- name: Remove TCP Monitor - Idempotent check
  bigip_monitor_tcp:
      name: "{{ monitor_name }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Remove TCP Monitor - Idempotent check
  assert:
      that:
          - not result|changed