---

banner_text: "This is a corporate device. Do not touch."
console_timeout: 600
gui_setup: "enabled"
lcd_display: "disabled"
mgmt_dhcp: "enabled"
net_reboot: "enabled"
quiet_boot: "disabled"
security_banner: "disabled"