---

vs_description: "Test Virtual Server"
vs_name: "my-virtual-server"
vs_port1: 443
vs_port2: 8080
vs_profiles1:
    - http
    - clientssl
vs_snat1: "Automap"
pool_name: "foo.pool"
node_host: "10.10.10.10"