---

- name: Set setup.run variable "on"
  bigip_sys_db:
      key: "{{ bigip_sys_db_key_1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      value: "{{ bigip_sys_db_val_1 }}"
  register: result

- name: Assert Set setup.run variable
  assert:
      that:
          - result|changed

- name: Set setup.run variable "on" - Idempotent check
  bigip_sys_db:
      key: "{{ bigip_sys_db_key_1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      value: "{{ bigip_sys_db_val_1 }}"
  register: result

- name: Assert Set setup.run variable "on" - Idempotent checl
  assert:
      that:
          - not result|changed

- name: Set setup.run variable "off"
  bigip_sys_db:
      key: "{{ bigip_sys_db_key_1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      value: "{{ bigip_sys_db_val_2 }}"
  register: result

- name: Assert Set setup.run variable "off"
  assert:
      that:
          - result|changed

- name: Set setup.run variable "off" - Idempotent check
  bigip_sys_db:
      key: "{{ bigip_sys_db_key_1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      value: "{{ bigip_sys_db_val_2 }}"
  register: result

- name: Assert Set setup.run variable "off" - Idempotent checl
  assert:
      that:
          - not result|changed

- name: Reset setup.run variable
  bigip_sys_db:
      key: "{{ bigip_sys_db_key_1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "reset"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      value: "{{ bigip_sys_db_val_1 }}"
  register: result

- name: Assert Reset setup.run variable
  assert:
      that:
          - result|changed

- name: Reset setup.run variable - Idempotent check
  bigip_sys_db:
      key: "{{ bigip_sys_db_key_1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "reset"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      value: "{{ bigip_sys_db_val_1 }}"
  register: result

- name: Assert Reset setup.run variable - Idempotent checl
  assert:
      that:
          - not result|changed

- name: No value and no reset
  bigip_sys_db:
      key: "{{ bigip_sys_db_key_1 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result
  failed_when: result|success