---

- name: Get GTM pool facts
  bigip_gtm_facts:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      include: "pool"
      fact_filter: "my_pool"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Get GTM pool facts
  assert:
      that:
          - result|changed