---

- include: setup.yaml

- name: Get GTM pool facts
  bigip_gtm_facts:
      include: "pool"
  register: result

- name: Assert Get GTM pool facts
  assert:
      that:
          - result|changed
          - "'pool' in result"

- name: Get GTM pool facts, many
  bigip_gtm_facts:
      include:
          - "pool"
          - "wide_ip"
  register: result

- name: Assert Get GTM pool facts, many
  assert:
      that:
          - result|changed
          - "'pool' in result"
          - "'wide_ip' in result"

- name: Get GTM pool facts with filter
  bigip_gtm_facts:
      include: "pool"
      filter: '{{ pool_filter }}'
  register: result

- name: Assert Get GTM pool facts with filter
  assert:
      that:
          - result|changed
          - result.pool|length == 1

- name: Get GTM pool facts with bad filter
  bigip_gtm_facts:
      include: "pool"
      filter: '{{ pool_filter_bad }}'
  register: result

- name: Assert Get GTM pool facts with bad filter
  assert:
      that:
          - result|changed
          - result.pool|length == 0
