---

- name: Get GTM pool facts
  bigip_gtm_facts:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      include: "pool"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Get GTM pool facts
  assert:
      that:
          - result|changed
          - "'pool' in result"

- name: Get GTM pool facts, many
  bigip_gtm_facts:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      include:
          - "pool"
          - "wide_ip"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Get GTM pool facts, many
  assert:
      that:
          - result|changed
          - "'pool' in result"
          - "'wide_ip' in result"

- name: Get GTM pool facts with filter
  bigip_gtm_facts:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      include: "pool"
      filter: '{{ pool_filter }}'
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Get GTM pool facts with filter
  assert:
      that:
          - result|changed
          - result.pool|length == 1

- name: Get GTM pool facts with bad filter
  bigip_gtm_facts:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      include: "pool"
      filter: '{{ pool_filter_bad }}'
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Get GTM pool facts with bad filter
  assert:
      that:
          - result|changed
          - result.pool|length == 0