---

- name: Create HTTP Monitor
  bigip_monitor_http:
      name: "{{ monitor_name }}"
      receive: "{{ receive_string }}"
      send: "{{ send_string }}"
      state: "present"
  register: result

- name: Assert Create HTTP Monitor
  assert:
      that:
          - result|changed

- name: Create HTTP Monitor - Idempotent check
  bigip_monitor_http:
      name: "{{ monitor_name }}"
      receive: "{{ receive_string }}"
      send: "{{ send_string }}"
      state: "present"
  register: result

- name: Assert Create HTTP Monitor - Idempotent check
  assert:
      that:
          - not result|changed

- name: Remove HTTP Monitor
  bigip_monitor_http:
      name: "{{ monitor_name }}"
      state: "absent"
  register: result

- name: Assert Remove HTTP Monitor
  assert:
      that:
          - result|changed

- name: Remove HTTP Monitor - Idempotent check
  bigip_monitor_http:
      name: "{{ monitor_name }}"
      state: "absent"
  register: result

- name: Assert Remove HTTP Monitor - Idempotent check
  assert:
      that:
          - not result|changed
