---

- name: Add virtual server
  bigip_virtual_server:
      all_profiles: "{{ vs_profiles1 }}"
      description: "{{ vs_description }}"
      destination: "{{ node_host }}"
      name: "{{ vs_name }}"
      partition: "{{ bigip_partition }}"
      password: "{{ bigip_password }}"
      port: "{{ vs_port1 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      snat: "{{ vs_snat1 }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"

- name: Modify Port of the Virtual Server
  bigip_virtual_server:
      name: "{{ vs_name }}"
      partition: "{{ bigip_partition }}"
      password: "{{ bigip_password }}"
      port: "{{ vs_port2 }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "present"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"

- name: Delete virtual server
  bigip_virtual_server:
      name: "{{ vs_name }}"
      partition: "{{ bigip_partition }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"