---

# Test the bigip_gtm_facts module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# bigip_gtm_facts module behaves as expected.
#
# Requirements:
#
#    GTM must be licensed for these tests to succeed
#
# Usage:
#
#    ansible-playbook -i notahost, playbooks/bigip_gtm_facts.yaml
#
# Examples:
#
#    Run all tests on the bigip_gtm_facts module
#
#    ansible-playbook -i notahost, playbooks/bigip_gtm_facts.yaml
#
# Tested platforms:
#
#    - 11.6.0
#    - 12.1.0 HF1
#

- name: Test the bigip_gtm_facts module
  hosts: f5-test
  connection: local

  roles:
      - bigip_gtm_facts