---

# Test the bigip_dns_record module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# bigip_dns_record module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, playbooks/bigip_dns_record.yaml
#
# Examples:
#
#    Run all tests on the bigip_dns_record module
#
#    ansible-playbook -i notahost, playbooks/bigip_dns_record.yaml
#
# Tested platforms:
#
#    - NA
#

- name: Test the bigip_dns_record module
  hosts: f5-test
  connection: local

  environment:
      F5_SERVER: "{{ inventory_hostname }}"
      F5_USER: "{{ bigip_username }}"
      F5_PASSWORD: "{{ bigip_password }}"
      F5_SERVER_PORT: "{{ bigip_port }}"
      F5_VALIDATE_CERTS: "{{ validate_certs }}"

  roles:
      - bigip_dns_record
