---

# Test the bigip_command module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# bigip_command module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, playbooks/bigip_command.yaml
#
# Examples:
#
#    Run all tests on the bigip_software module
#
#    ansible-playbook -i notahost, playbooks/bigip_command.yaml
#
# Tested platforms:
#
#    - NA
#

- name: Test the bigip_command module, root credentials with bash
  hosts: f5-test
  gather_facts: false
  connection: local

  environment:
      F5_SERVER: "{{ inventory_hostname }}"
      F5_USER: "root"
      F5_PASSWORD: "default"
      F5_SERVER_PORT: "{{ bigip_port }}"
      F5_VALIDATE_CERTS: "no"

  roles:
      - bigip_command
