---

# Test the bigip_device_dns module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# bigip_device_dns module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, playbooks/bigip_device_dns.yaml
#
# Examples:
#
#    Run all tests on the bigip_device_dns module
#
#    ansible-playbook -i notahost, playbooks/bigip_device_dns.yaml
#
# Tested platforms:
#
#    - 11.6.0
#    - 12.0.0
#

- name: Test the bigip_device_dns module
  hosts: f5-test
  connection: local

  roles:
      - __bigip_device_dns