---

vs_description: "Test Virtual Server"
vs_name: "my-virtual-server"
vs_port1: 443
vs_port2: 8080
vs_profiles1:
    - http
    - clientssl
vs_profiles_fasthttp:
    - "fastL4"
vs_snat1: "Automap"
pool_name: "foo.pool"
node_host: "10.10.10.10"
enabled_vlans: "net1"
snat_pool_name: "my-snat-pool"
members_list:
    - 10.10.10.10
    - 11.11.11.11

# Settings related to issue-53
i53_default_persistence_profile: "cookie"
i53_fallback_persistence_profile: "dest_addr"

# Settings related to issue-57
i57_partition: "GEN"